version: '3.8'
services:
  fintech-mysql:
    image: mysql:latest
    container_name: fintech-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=fintech
      - MYSQL_USER=fintech
      - MYSQL_DATABASE=fintech
      - MYSQL_PASSWORD=fintech
    ports:
      - 3306:3306

  fintech-redis:
    image: redis:latest
    container_name: fintech-redis
    ports:
      - 6379:6379
    networks:
      - redis-net

networks:
  redis-net: